import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[font]
size = 16
normal.family = "FiraCode Nerd Font Mono"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
dimensions = { columns = 640, lines = 400 }
padding = { x = 20, y = 20 }
dynamic_padding = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
blink_timeout = 15

[scrolling]
history = 5000
multiplier = 5

[selection]
semantic_escape_chars = ":@-./_~?&=%+#"

[mouse]
hide_when_typing = false
